=== jerzabek/mobilni-uredaji-dataset/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://or.jarza.cc/fer_2122_or_mobilni_uredaji.json",
  "type": "array",
  "title": "Mobilni uređaji dataset",
  "description": "FER 2122 Otvoreno računarstvo mobilni uređaji dataset",
  "items": {
    "type": "object",
    "title": "Mobile phone",
    "description": "Mobile phone in the dataset.",
    "required": [
      "name",
      "release_date",
      "brand",
      "processor",
      "width",
      "height",
      "thickness",
      "screen_size",
      "vertical_resolution",
      "horizontal_resolution",
      "charging_port",
      "headphone_jack",
      "microsd",
      "wireless_charging",
      "cameras"
    ],
    "properties": {
      "name": {
        "$id": "#/properties/name",
        "type": "string",
        "title": "The name schema",
        "description": "Name of the phone.",
        "examples": [
          "Galaxy A40"
        ]
      },
      "release_date": {
        "$id": "#/properties/release_date",
        "type": "string",
        "title": "The release_date schema",
        "description": "The release date of the phone.",
        "examples": [
          "2019-04-01"
        ]
      },
      "brand": {
        "$id": "#/properties/brand",
        "type": "string",
        "title": "The brand schema",
        "description": "Brand name of the phone manufacturer.",
        "examples": [
          "Samsung"
        ]
      },
      "processor": {
        "$id": "#/properties/processor",
        "type": "object",
        "title": "The processor schema",
        "description": "Processor details.",
        "default": {},
        "examples": [
          {
            "name": "Samsung Exynos 7885",
            "cores": 8,
            "clock_speed": 1.8,
            "brand": "Samsung"
          }
        ],
        "required": [
          "name",
          "cores",
          "clock_speed",
          "brand"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/processor/properties/name",
            "type": "string",
            "title": "The name schema",
            "description": "Name of the processor.",
            "default": "",
            "examples": [
              "Samsung Exynos 7885"
            ]
          },
          "cores": {
            "$id": "#/properties/processor/properties/cores",
            "type": "integer",
            "title": "The cores schema",
            "description": "Number of physical cores. Does not take into account different types of cores.",
            "default": 0,
            "examples": [
              8
            ]
          },
          "clock_speed": {
            "$id": "#/properties/processor/properties/clock_speed",
            "type": [
              "number",
              "null"
            ],
            "title": "The clock_speed schema",
            "description": "Clock speed of the processor in gigahertz.",
            "default": 0.0,
            "examples": [
              1.8
            ]
          },
          "brand": {
            "$id": "#/properties/processor/properties/brand",
            "type": "string",
            "title": "The brand schema",
            "description": "Brand name of the processor manufacturer.",
            "default": "",
            "examples": [
              "Samsung"
            ]
          }
        }
      },
      "width": {
        "$id": "#/properties/width",
        "type": "number",
        "title": "The width schema",
        "description": "Phone width in milimeters.",
        "default": 0.0,
        "examples": [
          144.3
        ]
      },
      "height": {
        "$id": "#/properties/height",
        "type": "number",
        "title": "The height schema",
        "description": "Phone height in milimeters.",
        "default": 0.0,
        "examples": [
          69.1
        ]
      },
      "thickness": {
        "$id": "#/properties/thickness",
        "type": "number",
        "title": "The thickness schema",
        "description": "Phone thickness in milimeters.",
        "default": 0.0,
        "examples": [
          7.9
        ]
      },
      "screen_size": {
        "$id": "#/properties/screen_size",
        "type": "number",
        "title": "The screen_size schema",
        "description": "The diagonal dimension of the screen in inches.",
        "default": 0.0,
        "examples": [
          5.9
        ]
      },
      "vertical_resolution": {
        "$id": "#/properties/vertical_resolution",
        "type": [
          "integer",
          "null"
        ],
        "title": "The vertical_resolution schema",
        "description": "Vertical resolution of the screen in pixels.",
        "default": 0,
        "examples": [
          2280
        ]
      },
      "horizontal_resolution": {
        "$id": "#/properties/horizontal_resolution",
        "type": [
          "integer",
          "null"
        ],
        "title": "The horizontal_resolution schema",
        "description": "Horizontal resolution of the screen in pixels.",
        "default": 0,
        "examples": [
          1080
        ]
      },
      "charging_port": {
        "$id": "#/properties/charging_port",
        "type": "string",
        "title": "The charging_port schema",
        "description": "The name of the charging port.",
        "default": "",
        "examples": [
          "USB-C"
        ]
      },
      "headphone_jack": {
        "$id": "#/properties/headphone_jack",
        "type": "boolean",
        "title": "The headphone_jack schema",
        "description": "Does the phone have a 3.5mm auxiliary jack.",
        "default": false,
        "examples": [
          true
        ]
      },
      "microsd": {
        "$id": "#/properties/microsd",
        "type": "boolean",
        "title": "The microsd schema",
        "description": "Does the phone have expandable storage in the form of a microsd slot.",
        "default": false,
        "examples": [
          true
        ]
      },
      "wireless_charging": {
        "$id": "#/properties/wireless_charging",
        "type": "boolean",
        "title": "The wireless_charging schema",
        "description": "Does the phone have wireless charging capabilities.",
        "default": false,
        "examples": [
          false
        ]
      },
      "cameras": {
        "$id": "#/properties/cameras",
        "type": "array",
        "title": "The cameras schema",
        "description": "Properties of the cameras on the phone",
        "default": [],
        "examples": [
          [
            {
              "description": "Main standard camera",
              "horizontal_resolution": null,
              "vertical_resolution": null,
              "resolution": 16,
              "apature": "f/1.7",
              "position": "back"
            },
            {
              "description": "Selfie camera",
              "horizontal_resolution": null,
              "vertical_resolution": null,
              "resolution": 25,
              "apature": "f/2.0",
              "position": "front"
            }
          ]
        ],
        "additionalItems": true,
        "items": {
          "$id": "#/properties/cameras/items",
          "anyOf": [
            {
              "$id": "#/properties/cameras/items/anyOf/0",
              "type": "object",
              "title": "The camera schema",
              "description": "A single camera",
              "default": {},
              "examples": [
                {
                  "description": "Main standard camera",
                  "horizontal_resolution": null,
                  "vertical_resolution": null,
                  "resolution": 16,
                  "apature": "f/1.7",
                  "position": "back"
                }
              ],
              "required": [
                "description",
                "horizontal_resolution",
                "vertical_resolution",
                "resolution",
                "apature",
                "position"
              ],
              "properties": {
                "description": {
                  "$id": "#/properties/cameras/items/anyOf/0/properties/description",
                  "type": "string",
                  "title": "The description schema",
                  "description": "Camera description.",
                  "default": "",
                  "examples": [
                    "Main standard camera"
                  ]
                },
                "horizontal_resolution": {
                  "$id": "#/properties/cameras/items/anyOf/0/properties/horizontal_resolution",
                  "type": [
                    "integer",
                    "null"
                  ],
                  "title": "The horizontal_resolution schema",
                  "description": "Horizontal resolution of the camera sensor in pixels.",
                  "default": null,
                  "examples": [
                    null
                  ]
                },
                "vertical_resolution": {
                  "$id": "#/properties/cameras/items/anyOf/0/properties/vertical_resolution",
                  "type": [
                    "integer",
                    "null"
                  ],
                  "title": "The vertical_resolution schema",
                  "description": "Vertical resolution of the camera sensor in pixels.",
                  "default": null,
                  "examples": [
                    null
                  ]
                },
                "resolution": {
                  "$id": "#/properties/cameras/items/anyOf/0/properties/resolution",
                  "type": [
                    "integer",
                    "null"
                  ],
                  "title": "The resolution schema",
                  "description": "Resolution of the camera described in megapixels.",
                  "default": 0,
                  "examples": [
                    16
                  ]
                },
                "apature": {
                  "$id": "#/properties/cameras/items/anyOf/0/properties/apature",
                  "type": "string",
                  "title": "The apature schema",
                  "description": "Camera apature.",
                  "default": "",
                  "examples": [
                    "f/1.7"
                  ]
                },
                "position": {
                  "$id": "#/properties/cameras/items/anyOf/0/properties/position",
                  "type": "string",
                  "title": "The position schema",
                  "description": "Describes the position of the camera",
                  "default": "",
                  "examples": [
                    "back"
                  ]
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== jerzabek/mobilni-uredaji-dataset/fer_2122_or_mobilni_uredaji.json
[{"name":"Galaxy A40","release_date":"2019-04-01","brand":"Samsung","processor":{"name":"Samsung Exynos 7885","cores":8,"clock_speed":1.8,"brand":"Samsung"},"width":144.3,"height":69.1,"thickness":7.9,"screen_size":5.9,"vertical_resolution":2280,"horizontal_resolution":1080,"charging_port":"USB-C","headphone_jack":true,"microsd":true,"wireless_charging":false,"cameras":[{"description":"Main standard camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":16,"apature":"f\/1.7","position":"back"},{"description":"Selfie camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":25,"apature":"f\/2.0","position":"front"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":5,"apature":"f\/2.2","position":"back"}]},{"name":"Galaxy A70","release_date":"2019-05-01","brand":"Samsung","processor":{"name":"Qualcomm Snapdragon 675","cores":8,"clock_speed":2,"brand":"Qualcomm"},"width":164.3,"height":76.7,"thickness":7.9,"screen_size":6.7,"vertical_resolution":2400,"horizontal_resolution":1080,"charging_port":"USB-C","headphone_jack":true,"microsd":true,"wireless_charging":false,"cameras":[{"description":"Selfie camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":32,"apature":"f\/2.0","position":"front"},{"description":"Depth sensor camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":5,"apature":"f\/2.2","position":"back"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":8,"apature":"f\/2.2","position":"back"},{"description":"Main standard camera","horizontal_resolution":3840,"vertical_resolution":2160,"resolution":32,"apature":"f\/1.7","position":"back"}]},{"name":"iPhone 13","release_date":"2021-09-24","brand":"Apple","processor":{"name":"A15 Bionic chip","cores":6,"clock_speed":null,"brand":"Apple"},"width":71.5,"height":146.7,"thickness":7.65,"screen_size":6.1,"vertical_resolution":1170,"horizontal_resolution":2532,"charging_port":"Lightning","headphone_jack":false,"microsd":false,"wireless_charging":true,"cameras":[{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/1.6","position":"back"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/2.4","position":"back"},{"description":"TrueDepth camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/2.2","position":"back"}]},{"name":"iPhone 13 Mini","release_date":"2021-09-24","brand":"Apple","processor":{"name":"A15 Bionic chip","cores":6,"clock_speed":null,"brand":"Apple"},"width":64.2,"height":131.5,"thickness":7.65,"screen_size":5.4,"vertical_resolution":1080,"horizontal_resolution":2340,"charging_port":"Lightning","headphone_jack":false,"microsd":false,"wireless_charging":true,"cameras":[{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/1.6","position":"back"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/2.4","position":"back"},{"description":"TrueDepth camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/2.2","position":"back"}]},{"name":"Mi 11","release_date":"2020-12-28","brand":"Xiaomi","processor":{"name":"Qualcomm Snapdragon 888","cores":8,"clock_speed":2.8,"brand":"Qualcomm"},"width":164.3,"height":74.6,"thickness":8.1,"screen_size":6.81,"vertical_resolution":3200,"horizontal_resolution":1440,"charging_port":"USB-C","headphone_jack":false,"microsd":false,"wireless_charging":true,"cameras":[{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":108,"apature":"f\/1.9","position":"back"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":13,"apature":"f\/2.4","position":"back"},{"description":"Macro lense camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":5,"apature":"f\/2.4","position":"back"},{"description":"Selfie camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":20,"apature":"f\/2.2","position":"front"}]},{"name":"Galaxy Note 20","release_date":"2020-08-21","brand":"Samsung","processor":{"name":"Exynos 990","cores":8,"clock_speed":2.73,"brand":"Samsung"},"width":161.6,"height":75.2,"thickness":8.3,"screen_size":6.7,"vertical_resolution":2400,"horizontal_resolution":1080,"charging_port":"USB-C","headphone_jack":false,"microsd":false,"wireless_charging":true,"cameras":[{"description":"Selife camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":10,"apature":"f\/2.2","position":"front"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/2.2","position":"back"},{"description":"Telephoto camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":64,"apature":"f\/2.0","position":"back"},{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/1.8","position":"back"}]},{"name":"iPhone 5","release_date":"2012-09-21","brand":"Apple","processor":{"name":"Apple A6","cores":2,"clock_speed":1.3,"brand":"Apple"},"width":123.8,"height":58.6,"thickness":7.6,"screen_size":4,"vertical_resolution":1136,"horizontal_resolution":640,"charging_port":"Lightning","headphone_jack":true,"microsd":false,"wireless_charging":false,"cameras":[{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":8,"apature":"f\/2.4","position":"back"},{"description":"Selfie camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":1,"apature":"f\/2.4","position":"front"}]},{"name":"Galaxy S4","release_date":"2013-04-01","brand":"Samsung","processor":{"name":"Exynos 5410","cores":8,"clock_speed":1.6,"brand":"Samsung"},"width":136.6,"height":69.8,"thickness":7.9,"screen_size":5,"vertical_resolution":1920,"horizontal_resolution":1080,"charging_port":"Micro USB","headphone_jack":true,"microsd":true,"wireless_charging":false,"cameras":[{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":13,"apature":"f\/2.2","position":"back"},{"description":"Selife camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":2,"apature":"f\/2.4","position":"front"}]},{"name":"Nokia 3310","release_date":"2000-09-01","brand":"Nokia","processor":{"name":"Texas Instruments MAD2WD1","cores":1,"clock_speed":0.13,"brand":"Texas Instruments"},"width":113,"height":48,"thickness":22,"screen_size":2.4,"vertical_resolution":320,"horizontal_resolution":240,"charging_port":"Proprietary","headphone_jack":false,"microsd":false,"wireless_charging":false,"cameras":[]},{"name":"Samsung Galaxy S10e","release_date":"2019-03-08","brand":"Samsung","processor":{"name":"Snapdragon 855","cores":8,"clock_speed":2.73,"brand":"Qualcomm"},"width":142.2,"height":69.9,"thickness":7.9,"screen_size":5.8,"vertical_resolution":2280,"horizontal_resolution":1080,"charging_port":"USB-C","headphone_jack":true,"microsd":true,"wireless_charging":false,"cameras":[{"description":"Standard main camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":12,"apature":"f\/2.4","position":"back"},{"description":"Ultrawide camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":16,"apature":"f\/2.2","position":"back"},{"description":"Selife camera","horizontal_resolution":null,"vertical_resolution":null,"resolution":10,"apature":"f\/1.9","position":"front"}]}]
